### ISSUE TITLE
Unable to add this library with yarn.

### ISSUE THREAD

**Issue by Siminn-teiturg** [birdofpreyru/react-native-audio#14]
I am unable to add this library with yarn.

`yarn add @dr.pogodin/react-native-audio`

```
error /Users/teiturg/GitHub/siminntv-react-native/node_modules/@dr.pogodin/react-native-audio: Command failed.
Exit code: 127
Command: pod-install
Arguments: 
Directory: /Users/teiturg/GitHub/siminntv-react-native/node_modules/@dr.pogodin/react-native-audio
Output:
/bin/sh: pod-install: command not found
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Is it possible this library is not compatible with yarn?

**Comment by birdofpreyru** [comment]
Hey @Siminn-teiturg , I don’t use yarn, thus haven’t tested it, and could miss something. It complaints about this script in package.json

https://github.com/birdofpreyru/react-native-audio/blob/09c40fa4a7519a739221b9fe05bee9fd01824b05/package.json#L33

Looking at it now, I guess it just shouldn’t be there - it just runs pod install for iOS projects, and only needed in the example app, or host codebase, not in the library package.json I guys - try to remove it.
